[package]
name = "bucket3rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
minijinja = "1.0"
comrak = "0.21"
sled = "0.34"
walkdir = "2.5"
time = { version = "0.3", features = ["parsing", "formatting"] }
serde_json = "1.0"
url = { version = "2.5", default-features = false }

[dev-dependencies]
tempfile = "3.12"
